services:
  weather-app:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: weather-app-container
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  # Optional: Add a development service
  weather-app-dev:
    build:
      context: ./react
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    container_name: weather-app-dev-container
    volumes:
      - ./react:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev